In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset=(pd.get_dummies(dataset,drop_first=True,dtype=int))

In [4]:
dataset=dataset.drop(columns='User ID', axis=1) # axis=0 is for rows

In [5]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [6]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [7]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [8]:
independent = dataset[['Age', 'EstimatedSalary','Gender_Male']]

In [9]:
independent.shape

(400, 3)

In [10]:
independent

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [11]:
dependent = dataset[['Purchased']]

In [12]:
dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [13]:
dependent.shape

(400, 1)

In [14]:
from sklearn.model_selection import train_test_split #Split Test and training data
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler #standarizing the value if we have abnormal variance
sc=StandardScaler()
x_train=sc.fit_transform(x_train) #Mean value and Standard deviation Value got calculated
x_test=sc.transform(x_test)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
param_grid = [
    {
        "solver": ["lbfgs", "newton-cg", "sag", "liblinear", "saga"],
        "penalty": ["l2"],
        "C": np.logspace(-3, 3, 7)  
    }
]
log_reg = LogisticRegression(max_iter=1000)
grid_search = GridSearchCV(estimator=log_reg, param_grid=param_grid, refit = "true", verbose=3,  cv=5, scoring="f1_weighted", n_jobs=-1)
grid_search = grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 35 candidates, totalling 175 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [16]:
re=grid_search.cv_results_
grid_prediction = grid_search.predict(x_test) #Predicting the test data
print("The R_score value for the best parameter {}:".format(grid_search.best_params_))

The R_score value for the best parameter {'C': np.float64(0.1), 'penalty': 'l2', 'solver': 'liblinear'}:

In [17]:
from sklearn.metrics import confusion_matrix #Calculating confusion matrix
cm = confusion_matrix(y_test,grid_prediction)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,grid_prediction)

In [18]:
#F1score - we are seperately evaluating the f1 score value, however we will be able to see in the clf-report
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_prediction,average='weighted')
print("The f1_score value for the best parameter {}:".format(grid_search.best_params_))

The f1_score value for the best parameter {'C': np.float64(0.1), 'penalty': 'l2', 'solver': 'liblinear'}:

In [19]:
print("The Confudion Matrix:", cm)

The Confudion Matrix: [[74  5]
 [10 31]]

In [20]:
print("The clf report:", clf_report)

The clf report:               precision    recall  f1-score   support

           0       0.88      0.94      0.91        79
           1       0.86      0.76      0.81        41

    accuracy                           0.88       120
   macro avg       0.87      0.85      0.86       120
weighted avg       0.87      0.88      0.87       120

In [21]:
#from sklearn.metrics import roc_auc_score
#roc_auc_score(y_test, grid_prediction.predict_proba(x_test)[:,1], average= 'weighted')
from sklearn.metrics import roc_auc_score

from sklearn.metrics import roc_auc_score
y_score = grid_prediction.predict_proba(x_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_score)
print("ROC-AUC Score:", roc_auc)

AttributeError: 'numpy.ndarray' object has no attribute 'predict_proba'

In [ ]:
age_input=float(input("Age:"))
salary_input=float(input("Salary:"))
sex_male_input=int(input("Sex_male_0 or 1:"))

In [ ]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

In [ ]:
dir(clf_report)

In [ ]:
import pickle
filename = "finalized_model_linear.sav"

In [ ]:
pickle.dump(classifier,open(filename, 'wb'))

In [ ]:
loaded_model = pickle.load(open("finalized_model_linear.sav", 'rb'))
result=loaded_model.predict([[25,6000000,1]])

In [ ]:
result